### ISSUE TITLE
提交指纹-[vmware-aria-operations-for-logs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#100]
### 测试目标

https://194.225.209.107/

### 指纹的Yaml规则

 ```yaml
name: vmware-aria-operations-for-logs
priority: 1
nuclei_tags:
  - - aria
    - vmware
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: 
       - <title>vRealize Log Insight -
    favicon_hash: []
```
