### ISSUE TITLE
修改指纹-[phpmyadmin]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#101]
### 测试目标

http://47.107.126.171/

### 指纹的Yaml规则

 ```yaml
name: phpmyadmin
priority: 3
nuclei_tags:
  - - phpmyadmin
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - href="phpmyadmin.css.php
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: phpmyadmin=
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: pma_lang=
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - pma_password
    favicon_hash: []
  - path: /phpmyadmin/index.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: phpmyadmin=
    keyword: []
    favicon_hash: []
  - path: /phpMyAdmin/index.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: phpmyadmin=
    keyword: []
    favicon_hash: []
  - path: /phpmyadmin/index.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: pma_lang=
    keyword: []
    favicon_hash: []
  - path: /phpMyAdmin/index.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: pma_lang=
    keyword: []
    favicon_hash: []
```
