### ISSUE TITLE
提交指纹-[phpstudy]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#103]
### 测试目标

http://43.142.97.124/

### 指纹的Yaml规则

 ```yaml
name: phpstudy
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '<title>phpStudy 探针 2'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '<title>站点创建成功-phpstudy for'
    favicon_hash: []
```
