### ISSUE TITLE
提交指纹-[ghostcms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#104]
### 测试目标

https://it-wonderland.com/

### 指纹的Yaml规则

 ```yaml
name: ghostcms
priority: 1
nuclei_tags:
  - - ghostcms
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - noopener">Powered by Ghost</a></div>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - Search this site" data-ghost-search><
    favicon_hash: []
```
