### ISSUE TITLE
提交指纹-[icinga]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#105]
### 测试目标

https://nagios.infracom.nl/

### 指纹的Yaml规则

 ```yaml
name: icinga
priority: 1
nuclei_tags:
  - - icinga
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Icinga Web 2 Login</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - mask-icon" href="/icingaweb2/img/website-icon.svg" color=
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 466b3dcce4a3c13f44dd0dc824b1e328
```
