### ISSUE TITLE
提交指纹-[sitecore]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#107]
### 测试目标

https://www.sporthorseinsurance.com/

### 指纹的Yaml规则

 ```yaml
name: sitecore
priority: 1
nuclei_tags:
  - - sitecore
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - alt="Sitecore" id="scLogo" />
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - title="Sitecore Documentation site">
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 7e7727c980ccf9d9a3d11bbc702f6363
```
