### ISSUE TITLE
修改指纹-[jeecgboot]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#108]
### 测试目标

https://admin.dzm12315.com/

### 指纹的Yaml规则

 ```yaml
name: jeecgboot
priority: 1
nuclei_tags:
  - - jeecg
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - JeecgBoot
      - polyfill_
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - onlinePreviewDomainURL'] = 'http://fileview.jeecg.com
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - dc7a0b69060a0262530b47b46ba7f9b6
```
