### ISSUE TITLE
修改指纹-[avtech-video-web-server]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#109]
### 测试目标

http://111.243.198.14/

### 指纹的Yaml规则

 ```yaml
name: avtech-video-web-server
priority: 2
nuclei_tags:
  - - avtech
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - please visit 'www.avtech.com.tw'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Remote Surveillance, Any time &amp; Any where</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /av732e/setup.exe
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - ed8cf53ef6836184587ee3a987be074a
```
