### ISSUE TITLE
提交指纹-[odoo]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#110]
### 测试目标

http://160.177.243.221:2010/

### 指纹的Yaml规则

 ```yaml
name: odoo
priority: 1
nuclei_tags:
  - - odoo
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - odoo.__session_info__ = {
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <script id="web.layout.odooscript
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - a342fe863a8e41dff2a55410c7f118c5
```
