### ISSUE TITLE
提交指纹-[ruckus-wireless]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#111]
### 测试目标

https://45.49.183.79/

### 指纹的Yaml规则

 ```yaml
name: ruckus-wireless
priority: 1
nuclei_tags:
  - - ruckus
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Ruckus Wireless Admin</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - alt="Ruckus Wireless" title=
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - ed8cf53ef6836184587ee3a987be074a
```
