### ISSUE TITLE
提交指纹-[teslamate]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#112]
### 测试目标

http://121.40.203.237/

### 指纹的Yaml规则

 ```yaml
name: teslamate
priority: 1
nuclei_tags:
  - - teslamate
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <img alt="TeslaMate" src=
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 0e3b30468f89fa98cb22983c89e49d0a
```
