### ISSUE TITLE
提交指纹-[solarview-compact]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#113]
### 测试目标

http://ms5ccbb513.ap.nuro.jp/

### 指纹的Yaml规则

 ```yaml
name: solarview-compact
priority: 1
nuclei_tags:
  - - solarview
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - Refresh" content="3; URL=Solar_Menu.php
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash: []
```
