### ISSUE TITLE
修改指纹-[solarview-compact]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#115]
### 测试目标

http://115.179.100.230.ap.gmobb-fix.jp/

### 指纹的Yaml规则

 ```yaml
name: solarview-compact
priority: 1
nuclei_tags:
  - - solarview
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - Refresh" content="3; URL=Solar_Menu.php
    favicon_hash: []
```
