### ISSUE TITLE
修改指纹-[jeecms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#116]
### 测试目标

http://www.jxfhtc.com/

### 指纹的Yaml规则

 ```yaml
name: jeecms
priority: 1
nuclei_tags:
  - - jeecms
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <script src="/r/cms/www/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <script src="/u/cms/www/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - www.jeecms.com
    favicon_hash: []
```
