### ISSUE TITLE
提交指纹-[cisco-ssl-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#117]
### 测试目标

https://wh-vpn.dofun.cn:6443/

### 指纹的Yaml规则

 ```yaml
name: cisco-ssl-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: webvpncontext=
    keyword: []
    favicon_hash: []
```
