### ISSUE TITLE
提交指纹-[pear-project]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#118]
### 测试目标

http://124.221.159.186/

### 指纹的Yaml规则

 ```yaml
name: pear-project
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4a912be52af99e4407d53651ccde64e6
```
