### ISSUE TITLE
修改指纹-[apache-shiro]

### ISSUE THREAD

**Issue by lsadaharu** [0x727/FingerprintHub#12]
### 测试目标

http://wczz.net

### 指纹的Yaml规则

 ```yaml
name: apache-shiro
priority: 3
nuclei_tags:
  - - "shiro"
    - "apache"
fingerprint:
  - path: /
    request_method: post
    request_headers:
      Cookie: rememberMe=admin;rememberMe-K=admin
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: rememberMe=deleteMe
    keyword: [ ]
    favicon_hash: [ ]
  - path: /
    request_method: get
    request_headers:
      Cookie: rememberMe=admin;rememberMe-K=admin
    request_data: ''
    status_code: 0
    headers:
      Set-Cookie: rememberMe=deleteMe
    keyword: [ ]
    favicon_hash: [ ]
  - path: /
    request_method: get
    request_headers: { }
    request_data: ''
    status_code: 0
    headers: { }
    keyword:
      - </i> shiro</li>
    favicon_hash: [ ]
```
