### ISSUE TITLE
修改指纹-[microsoft-exchange]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#122]
### 测试目标

https://srvexchange.zanolli.it/

### 指纹的Yaml规则

 ```yaml
name: microsoft-exchange
priority: 3
nuclei_tags:
  - - exchange
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 302
    headers:
      Location: /owa/
      Server: Microsoft
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <!-- owapage = asp.auth_logon_aspx
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /exchweb/bin/auth/owalogon.asp
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /exchweb/bin/auth/owalogon.asp?url=
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - href="/owa/auth/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - window.location.replace("/owa/" + window.location.hash);</script></head><body></body>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <meta http-equiv="refresh" content="0;url=/owa">
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - themes/resources/segoeui-semibold.ttf
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <div class="signinheader">outlook</div>
      - owalogocontainer
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /owa/
      - owapage = asp.auth_logon_aspx
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /owa/
      - showpasswordcheck
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <div class="signInHeader">Outlook</div>
    favicon_hash: []
```
