### ISSUE TITLE
修改指纹-[spring-framework]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#124]
### 测试目标

http://aipromoter.com:8080/

### 指纹的Yaml规则

 ```yaml
name: spring-framework
priority: 2
nuclei_tags:
  - - springboot
  - - springframework
  - - spring
    - vmware
  - - spring
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - whitelabel error page
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '","status":404,"error":"Not Found","message":"No message available","path":"/'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Www-Authenticate: Basic realm="Spring"
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      X-Application-Context:
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 0488faca4c19046b94d07c3ee83cf9d66
```
