### ISSUE TITLE
修改指纹-[apache-tomcat]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#126]
### 测试目标

http://aipromoter.com:8080/

### 指纹的Yaml规则

 ```yaml
name: apache-tomcat
priority: 3
nuclei_tags:
  - - tomcat
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 404
    headers: {}
    keyword:
      - <h3>Apache Tomcat/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - <title>Apache Tomcat/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /manager/html
      - /manager/status
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - href="tomcat.css
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - this is the default tomcat home page
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <h3>apache tomcat
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      x-powered-by: Tomcat
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Server: Apache-Coyote/
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4644f2d45601037b8423d45e13194c93
```
