### ISSUE TITLE
提交指纹-[hikvision-isecure-center]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#127]
### 测试目标

https://110.90.136.140:1443/

### 指纹的Yaml规则

 ```yaml
name: hikvision-isecure-center
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4209fe52e5c15345d0a1250f68a14d1e
```
