### ISSUE TITLE
提交指纹-[lucee]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#128]
### 测试目标

http://185.27.247.101/

### 指纹的Yaml规则

 ```yaml
name: lucee
priority: 3
nuclei_tags:
  - - lucee
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 'png" alt="Lucee">'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 'by the Lucee Association Switzerland</p>'
    favicon_hash: []
```
