### ISSUE TITLE
提交指纹-[kafka-center]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#129]
### 测试目标

http://120.27.233.140:10012/

### 指纹的Yaml规则

 ```yaml
name: kafka-center
priority: 3
nuclei_tags:
  - - kafka
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Kafka Center</title>
    favicon_hash: []
```
