### ISSUE TITLE
提交指纹-[华为云堡垒机]

### ISSUE THREAD

**Issue by cn-kali-team** [0x727/FingerprintHub#13]
### 测试目标

https://114.116.251.84

### 指纹的Yaml规则

```yaml
name: 华为云堡垒机
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - event_onusbkeychange=OnUsbKeyChange
      - id=mTokenPlugin
      - value=pluginLoaded
    favicon_hash: []
```
