### ISSUE TITLE
修改指纹-[奇安信-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#131]
### 测试目标

https://163.171.201.63:3333/

### 指纹的Yaml规则

 ```yaml
name: 奇安信-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - QianxinVPN
      - 卸载奇安信VPN
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4cf31d7e53197f79b435b66cc8cb3098
```
