### ISSUE TITLE
提交指纹-[check-point-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#133]
### 测试目标

https://46.22.170.3/

### 指纹的Yaml规则

 ```yaml
name: check-point-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 'check point software technologies'
      - '<img src="/sslvpn/login/images/companylogo.png'
    favicon_hash: []
```
