### ISSUE TITLE
提交指纹-[topsec-ssl-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#134]
### 测试目标

https://183.129.214.114/

### 指纹的Yaml规则

 ```yaml
name: topsec-ssl-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '<img id="topsecsvload'
      - '<div id="upgrade_sslvpnclient'
    favicon_hash: []
```
