### ISSUE TITLE
提交指纹-[sangfor-ssl-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#135]
### 测试目标

https://47.96.80.52:4433/

### 指纹的Yaml规则

 ```yaml
name: sangfor-ssl-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '/portal",right:0}];'
      - '/por/login_psw.csp'
    favicon_hash: []
```
