### ISSUE TITLE
修改指纹-[pulsesecure-ssl-vpn]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#136]
### 测试目标

https://111.160.157.2

### 指纹的Yaml规则

 ```yaml
name: pulsesecure-ssl-vpn
priority: 3
nuclei_tags:
  - - pulsesecure
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Pulse Connect Secure</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <b>pulse connect secure</b>
    favicon_hash: []
```
