### ISSUE TITLE
提交指纹-[webuploader]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#137]
### 测试目标

http://ppp.gosafenet.com.cn/

### 指纹的Yaml规则

 ```yaml
name: webuploader
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /webuploader.min.js"></script>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /webuploader.js"></script>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /webuploader.css" rel="stylesheet
    favicon_hash: []
```
