### ISSUE TITLE
提交指纹-[thinkjs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#138]
### 测试目标

https://54.207.240.153/

### 指纹的Yaml规则

 ```yaml
name: thinkjs
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      X-Powered-By: thinkjs
    keyword: []
    favicon_hash: []
```
