### ISSUE TITLE
提交指纹-[nuxtjs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#139]
### 测试目标

http://1.15.232.61:3000

### 指纹的Yaml规则

 ```yaml
name: nuxtjs
priority: 1
nuclei_tags:
  - - nuxtjs
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - __nuxt
      - buildAssetsDir
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - buildAssetsDir
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 5c1028350a39fb9e5a9bfbe280326e28
```
