### ISSUE TITLE
提交指纹-[hfish]

### ISSUE THREAD

**Issue by cn-kali-team** [0x727/FingerprintHub#14]
### 测试目标

http://8.130.53.108:9001

### 指纹的Yaml规则

 ```yaml
name: hfish
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>hfish
      - src="/static/images/hfish.png"
      - href="https://github.com/hacklcx/hfish"
    favicon_hash: []
```
