### ISSUE TITLE
修改指纹-[metersphere]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#140]
### 测试目标

https://metersphere.richingcloud.com/

### 指纹的Yaml规则

 ```yaml
name: metersphere
priority: 1
nuclei_tags:
  - - metersphere
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - <title>MeterSphere
    favicon_hash: []
```
