### ISSUE TITLE
修改指纹-[bitbucket]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#141]
### 测试目标

http://202.105.96.141:9090/

### 指纹的Yaml规则

 ```yaml
name: bitbucket
priority: 3
nuclei_tags:
  - - bitbucket
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - bitbucket.page.login
    favicon_hash: []
```
