### ISSUE TITLE
修改指纹-[dedecms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#142]
### 测试目标

https://yx.biduwenxue.com/

### 指纹的Yaml规则

 ```yaml
name: dedecms
priority: 3
nuclei_tags:
  - - dedecms
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <a href=http://www.dedecms.com target='_blank'>Power by DedeCms</a>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - power by dedecms
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - http://www.dedecms.com/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /templets/default/style/dedecms.css
      - dedecms
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <div><h3>dedecms error warning!</h3>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - name="dede_fields
      - name="dede_fieldshash
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - content="order by dede58.com" />
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <form  name="formsearch" action="/plus/search.php">
      - name="q"
    favicon_hash: []
```
