### ISSUE TITLE
修改指纹-[wordpress]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#143]
### 测试目标

http://nuclearcompetition2023.enen.bme.hu/

### 指纹的Yaml规则

 ```yaml
name: wordpress
priority: 3
nuclei_tags:
  - - wordpress
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - /wp-content/themes/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 'name="generator" content="wordpress '
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /wp-includes/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <link rel='stylesheet' id='wp-block-library-css
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4cf31d7e53197f79b435b66cc8cb3098
```
