### ISSUE TITLE
提交指纹-[chamilo]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#144]
### 测试目标

http://intranet.inm-lex.ro/

### 指纹的Yaml规则

 ```yaml
name: chamilo
priority: 3
nuclei_tags:
  - - chamilo
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <meta name="generator" content="Chamilo
    favicon_hash: []
```
