### ISSUE TITLE
提交指纹-[nuxtjs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#145]
### 测试目标

https://app.orch.one/

### 指纹的Yaml规则

 ```yaml
name: nuxtjs
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - __nuxt
      - buildAssetsDir
    favicon_hash: []
```
