### ISSUE TITLE
提交指纹-[jianmu]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#146]
### 测试目标

https://ci.litchinn.com

### 指纹的Yaml规则

 ```yaml
name: jianmu
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - a60399bff2cbc1462547d9a38284264d
```
