### ISSUE TITLE
修改指纹-[wordpress]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#147]
### 测试目标

http://transport.perfect-sitebank.com/

### 指纹的Yaml规则

 ```yaml
name: wordpress
priority: 3
nuclei_tags:
  - - wordpress
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - /wp-content/themes/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 'name="generator" content="wordpress '
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /wp-includes/
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <link rel='stylesheet' id='wp-block-library-css
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - \/wp-admin\/admin-ajax.php","
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - /wp-content/uploads/
    favicon_hash: []
```
