### ISSUE TITLE
提交指纹-[gravcms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#148]
### 测试目标

https://vmd65142.contaboserver.net

### 指纹的Yaml规则

 ```yaml
name: gravcms
priority: 3
nuclei_tags:
  - - grav
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 200
    headers: {}
    keyword:
      - <meta name="generator" content="GravCMS
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 0b11a9699ae33de62a1d05be8f733486
```
