### ISSUE TITLE
提交指纹-[xwiki]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#152]
### 测试目标

https://wiki.qsolution.ru/

### 指纹的Yaml规则

 ```yaml
name: xwiki
priority: 3
nuclei_tags:
  - - xwiki
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - data-xwiki-reference=
    favicon_hash: []
```
