### ISSUE TITLE
提交指纹-[nginx-webui]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#153]
### 测试目标

http://20.243.236.55:8080/

### 指纹的Yaml规则

 ```yaml
name: nginx-webui
priority: 3
nuclei_tags:
  - - nginxwebui
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>nginxWebUI</title>
    favicon_hash: []
```
