### ISSUE TITLE
提交指纹-[metabase]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#154]
### 测试目标

http://loveat.la:3000/

### 指纹的Yaml规则

 ```yaml
name: metabase
priority: 3
nuclei_tags:
  - - metabase
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - _metabaseBootstrap
      - _metabaseLocalization
    favicon_hash: []
```
