### ISSUE TITLE
提交指纹-[alibaba-anyproxy]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#155]
### 测试目标

http://tonghopkienthuc.wiki:8002/

### 指纹的Yaml规则

 ```yaml
name: alibaba-anyproxy
priority: 3
nuclei_tags:
  - - anyproxy
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>AnyProxy</title>
      - dist/main.css
    favicon_hash: []
```
