### ISSUE TITLE
提交指纹-[mobileiron-mdm]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#157]
### 测试目标

https://mi2.llv.li/

### 指纹的Yaml规则

 ```yaml
name: mobileiron-mdm
priority: 3
nuclei_tags:
  - - mobileiron
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /whitelabel/mobileiron/img/favicon.ico
    favicon_hash: []
```
