### ISSUE TITLE
提交指纹-[yonyou-nc-cloud]

### ISSUE THREAD

**Issue by Rvn0xsy** [0x727/FingerprintHub#158]
### 测试目标

http://182.140.224.187:10001/

### 指纹的Yaml规则

 ```yaml
name: yonyou-nc-cloud
priority: 3
nuclei_tags:
 - - "yonyou-nc-cloud"
   - "yonyou-nc-cloud"
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <meta http-equiv=refresh content=0;url=nccloud>
   favicon_hash: [ ]
```
