### ISSUE TITLE
提交指纹-[yonyou-grp-u8]

### ISSUE THREAD

**Issue by Rvn0xsy** [0x727/FingerprintHub#16]
### 测试目标

http://211.149.157.219:8001

### 指纹的Yaml规则

 ```yaml
name: yonyou-grp-u8
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - window.location.replace("login.jsp?up=1");
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash: ["b41be1ccc6f9f2894e0cfcf23acf5fc0"]
```
