### ISSUE TITLE
提交指纹-[lexmark]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#160]
### 测试目标

http://188.36.121.249:82/

### 指纹的Yaml规则

 ```yaml
name: lexmark
priority: 3
nuclei_tags:
  - - lexmark
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Lexmark
      - /Status
    favicon_hash: []
```
