### ISSUE TITLE
修改指纹-[phpstudy]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#161]
### 测试目标

http://184.168.22.188:9080/

### 指纹的Yaml规则

 ```yaml
name: phpstudy
priority: 3
nuclei_tags:
  - - phpstudy
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>phpStudy 探针 2
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>站点创建成功-phpstudy for
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>404 错误 - phpstudy</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Server: xpserver
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 406165e1c4ec82ac49847ca8e7810bae
```
