### ISSUE TITLE
修改指纹-[phpok]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#162]
### 测试目标

http://en.sagex.cn/

### 指纹的Yaml规则

 ```yaml
name: phpok
priority: 3
nuclei_tags:
  - - phpok
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <meta name="author" content="phpok,
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 1091f8722e63111e50302ecbfdd6e975
      - aea2803f24d6f4156bde7681f17c3253
```
