### ISSUE TITLE
提交指纹-[h3c-router]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#163]
### 测试目标

http://220.174.209.176:10000/

### 指纹的Yaml规则

 ```yaml
name: h3c-router
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - restore.htm
      - service@h3c.com
    favicon_hash: []
```
