### ISSUE TITLE
提交指纹-[panabit-ixcache]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#164]
### 测试目标

https://59.35.95.43:9444/

### 指纹的Yaml规则

 ```yaml
name: panabit-ixcache
priority: 3
nuclei_tags:
  - - ixcache
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>iXCache</title>
    favicon_hash: []
```
