### ISSUE TITLE
修改指纹-[apache-apisix]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#168]
### 测试目标

https://www.saohutv130.cc

### 指纹的Yaml规则

 ```yaml
name: apache-apisix
priority: 3
nuclei_tags:
  - - apisix
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      server: apisix
    keyword:
      - '{"error_msg":"404 Route Not Found"}'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      server: apisix
    keyword: []
    favicon_hash: []
```
