### ISSUE TITLE
提交指纹-[kong]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#169]
### 测试目标

http://40.91.75.199/

### 指纹的Yaml规则

 ```yaml
name: kong
priority: 3
nuclei_tags:
  - - kong
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Server: kong
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      via: kong
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      X-Kong-Response-Latency:
    keyword: []
    favicon_hash: []
```
