### ISSUE TITLE
修改指纹-[spring-boot-admin]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#171]
### 测试目标

http://test-monitor.edilion.com/

### 指纹的Yaml规则

 ```yaml
name: spring-boot-admin
priority: 2
nuclei_tags:
  - - springboot
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - spring boot admin
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <img src="assets/img/icon-spring-boot-admin.svg
    favicon_hash: []
```
