### ISSUE TITLE
提交指纹-[pypiserver]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#173]
### 测试目标

https://package.cloud.newtech.co.nz/

### 指纹的Yaml规则

 ```yaml
name: pypiserver
priority: 3
nuclei_tags:
  - - pypiserver
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Welcome to pypiserver!</title>
    favicon_hash: []
```
