### ISSUE TITLE
提交指纹-[expressjs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#174]
### 测试目标

http://www.smc.dscloud.me:9853/

### 指纹的Yaml规则

 ```yaml
name: expressjs
priority: 3
nuclei_tags:
  - - expressjs
  - - nodejs
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      X-Powered-By: Express
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <p>Welcome to Express</p>
    favicon_hash: []
```
