### ISSUE TITLE
修改指纹-[apache-apisix]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#176]
### 测试目标

http://124.112.102.25:30000/

### 指纹的Yaml规则

 ```yaml
name: apache-apisix
priority: 3
nuclei_tags:
  - - apisix
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      server: apisix
    keyword: []
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      server: apisix
    keyword:
      - '{"error_msg":"404 Route Not Found"}'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 404
    headers:
      server: nginx
      content-type: text/plain
    keyword:
      - '{"error_msg":"404 Route Not Found"}'
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 404
    headers:
      server: openresty
      content-type: text/plain
    keyword:
      - '{"error_msg":"404 Route Not Found"}'
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 404
    headers:
      server: tengine
      content-type: text/plain
    keyword:
      - '{"error_msg":"404 Route Not Found"}'

```
