### ISSUE TITLE
提交指纹-[sentry]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#178]
### 测试目标

https://sentry.allsafe.3mk.pl/

### 指纹的Yaml规则

 ```yaml
name: sentry
priority: 3
nuclei_tags:
 - - sentry
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - '<title>Sign In | Sentry</title>'
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - 'Sentry.ConfigStore.loadInitialData({'
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword: []
   favicon_hash:
     - 415ab63d14960e66d7f026d1adcdd2f4
```
