### ISSUE TITLE
提交指纹-[mojarra-jsf]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#179]
### 测试目标

http://27.2.122.181:9090

### 指纹的Yaml规则

 ```yaml
name: mojarra-jsf
priority: 3
nuclei_tags:
 - - mojarra
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - '<input type="hidden" name="javax.faces.ViewState"'
   favicon_hash: []
```
