### ISSUE TITLE
修改指纹-[ruoyi-system]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#181]
### 测试目标

http://38.6.189.159:8081/

### 指纹的Yaml规则

 ```yaml
name: ruoyi-system
priority: 3
nuclei_tags:
  - - ruoyi
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - href="/ruoyi/css/ry-ui.css
      - src="/ruoyi/js/ry-ui.js
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - e49fd30ea870c7a820464ca56a113e6e
```
