### ISSUE TITLE
提交指纹-[anwang-wayosac]

### ISSUE THREAD

**Issue by labixx21** [0x727/FingerprintHub#186]
### 测试目标

http://175.169.232.197:800/

### 指纹的Yaml规则

```yaml
name: anwang-wayosac
priority: 3
nuclei_tags:
  - [wayosac,anwang]
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash: ["715c49c5512d763084a4082c27d935e1"]
```
