### ISSUE TITLE
提交指纹-[hikvision-ip-camera]

### ISSUE THREAD

**Issue by zeroChen00** [0x727/FingerprintHub#187]
### 测试目标

http://115.96.25.211

### 指纹的Yaml规则

```yaml
name: hikvision-ip-camera
priority: 3
nuclei_tags:
  - - "Hikvision"
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash: ['89b932fcc47cf4ca3faadb0cfdef89cf']
```
