### ISSUE TITLE
提交指纹-[huawei-ssl-vpn]

### ISSUE THREAD

**Issue by akkuman** [0x727/FingerprintHub#19]
### 测试目标

https://218.76.27.162:4434/

### 指纹的Yaml规则

 ```yaml
name: huawei-ssl-vpn
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - Clear SSL cache successfully
      - getCookie("SGDPortal")
      - SVN_GetLoginContextValue(
    favicon_hash: []
```
