### ISSUE TITLE
提交指纹-[common-login]

### ISSUE THREAD

**Issue by kuron3k0** [0x727/FingerprintHub#205]
### 测试目标

https://www.tyztik701.com/

### 指纹的Yaml规则

 ```yaml
id: common-login
info:
  name: common-login
  author: kuron3k0
  tags: detect,tech,login
  severity: info
  metadata:
    product: common-login
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - type="password
    - type='password
    - type=password
    case-insensitive: true
```
