### ISSUE TITLE
提交指纹-[shopxo]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#21]
### 测试目标

https://d2.shopxo.vip/

### 指纹的Yaml规则

```yaml
name: shopxo
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 6774ad0b380e1ffeee4e380352e51f15
```
