### ISSUE TITLE
提交指纹-[phpok]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#22]
### 测试目标

http://phpok.com/

### 指纹的Yaml规则

```yaml
name: phpok
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 1091f8722e63111e50302ecbfdd6e975
      - aea2803f24d6f4156bde7681f17c3253
```
