### ISSUE TITLE
提交指纹-[leadshop]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#25]
### 测试目标

https://www.leadshop.vip/

### 指纹的Yaml规则

 ```yaml
name: leadshop
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 34e851938a4a941ce6318d62253892ec
      - 5b0665d0447da9c06646da8f282bf372
```
