### ISSUE TITLE
提交指纹-[dtcloud]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#26]
### 测试目标

http://www.dtcloud360.com/

### 指纹的Yaml规则

 ```yaml
name: dtcloud
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - DTCloud
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 49fe0618acdcd7c9dc443faca20d7bd9
```
