### ISSUE TITLE
提交指纹-[jumpserver]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#27]
### 测试目标

http://jump.chuangcache.com/core/auth/login/

### 指纹的Yaml规则

 ```yaml
name: jumpserver
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - jumpserver
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 20334371817c7368907b5ea52aab2d9e
```
