### ISSUE TITLE
提交指纹-[万户ezoffice协同管理平台]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#28]
### 测试目标

http://39.106.74.130/defaultroot/portal.jsp?access=oa

### 指纹的Yaml规则

 ```yaml
name: 万户ezoffice协同管理平台
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - ezOFFICE协同管理平台
    favicon_hash: []
  - path: /favicon.ico
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - fa1f01d0392d60663d8ce936fe06096a
```
