### ISSUE TITLE
提交指纹-[中远麒麟iAudit堡垒机]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#29]
### 测试目标

https://124.71.4.11:1443/admin.php

### 指纹的Yaml规则

 ```yaml
name: 中远麒麟iAudit堡垒机
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 0c3f9b770b14279fef0b5a827406c3ae
```
