### ISSUE TITLE
提交指纹-[紫光档案管理系统]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#30]
### 测试目标

http://47.118.21.129/

### 指纹的Yaml规则

 ```yaml
name: 紫光档案管理系统
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 紫光档案管理系统
    favicon_hash:
      - 3e2ee25dc73811fe2a697deefe447017
```
