### ISSUE TITLE
提交指纹-[casdoor]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#31]
### 测试目标

http://124.221.115.191:8008/

### 指纹的Yaml规则

 ```yaml
name: casdoor
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>casdoor
      - casdoor/manifest.json
    favicon_hash: [ ]
```
