### ISSUE TITLE
提交指纹-[h5s-video-platform]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#32]
### 测试目标

http://60.248.138.142:8080

### 指纹的Yaml规则

 ```yaml
name: 零视科技-H5S视频平台
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - h5s视频平台|web
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 71d350f81224c181b2fc5851fc61b0ba
```
