### ISSUE TITLE
提交指纹-[roxy-wi]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#33]
### 测试目标

https://demo.roxy-wi.org/app/login.py

### 指纹的Yaml规则

 ```yaml
name: Roxy-Wi
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 115a65bda90efe228d692227dc196f74
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - Roxy-WI
    favicon_hash: []
```
