### ISSUE TITLE
提交指纹-[iceflow-vpn]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#34]
### 测试目标

http://38.6.155.108/index.php

### 指纹的Yaml规则

 ```yaml
name: iceflow
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: 
      - iceflow/tweb
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - www.icevpn.org
    favicon_hash: []
```
