### ISSUE TITLE
提交指纹-[canal-admin]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#35]
### 测试目标

http://38.6.155.108/index.php

### 指纹的Yaml规则

 ```yaml
name: canal-admin
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - canal admin
    favicon_hash: []
```
