### ISSUE TITLE
提交指纹-[zkteco]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#37]
### 测试目标

http://38.6.155.108

### 指纹的Yaml规则

 ```yaml
name: 熵安云通智慧园区v8800
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 67c76f647cb8d42a71eb295e003394d2 
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 智慧园区综合管理平台
    favicon_hash: []
```
