### ISSUE TITLE
提交指纹-[crmeb]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#38]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: crmeb
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 699adaf4da1b0dc76ea5464df13755d7 
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <h1>crmeb</h1>
    favicon_hash: []
```
