### ISSUE TITLE
提交指纹-[niushop]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#39]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: niushop
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 4b320a972023a99c21bffa7267ba6546
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - niushop
    favicon_hash: []
```
