### ISSUE TITLE
提交指纹-[cool-admin]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#40]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: CoolAdmin
priority: 3
nuclei_tags:
 - []
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword: []
   favicon_hash:
     - 0a1a4905050aeb5bcc9d0c124bb96eb6
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - cool-admin
   favicon_hash: []
```
