### ISSUE TITLE
提交指纹-[coreshop]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#41]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: coreshop
priority: 3
nuclei_tags:
- []
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword: []
  favicon_hash:
    - ac08a66b033430e3034e395cc9f04533
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
    - coreshop
  favicon_hash: []
```
