### ISSUE TITLE
提交指纹-[gocd-params]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#42]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: gocd-params
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - 423a583332e4232659690dead75184e6
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - gocd-params
    favicon_hash: []
```
