### ISSUE TITLE
提交指纹-[muhttpd]

### ISSUE THREAD

**Issue by xz-zone** [0x727/FingerprintHub#43]
### 测试目标

http://38.6.155.108/

### 指纹的Yaml规则

 ```yaml
name: muhttpd
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash:
      - e50cc7cc4f8d7f2346d901c35dee3a5f
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - 2017 arris enterprises, llc. all rights reserved.
    favicon_hash: []
```
