### ISSUE TITLE
提交指纹-[apache-apisix]

### ISSUE THREAD

**Issue by pwnhxl** [0x727/FingerprintHub#46]
### 测试目标

http://www.easinote-beta-imlizhi-store-https.test.seewo.com/

### 指纹的Yaml规则

 ```yaml
name: apache-apisix
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {"server":"apisix"}
    keyword:
      - '{"error_msg":"404 Route Not Found"}'
    favicon_hash: []
```
