### ISSUE TITLE
提交指纹-[MinIO]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#47]
### 测试目标

http://ktx-cctv.dientoanbachkhoa.vn:9001/

### 指纹的Yaml规则

 ```yaml
name: minio-browser
priority: 3
nuclei_tags:
  - - minio
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '<title>MinIO Console</title>'
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - href="/minio/loader.css"
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>MinIO Browser</title>
    favicon_hash: []
```
