### ISSUE TITLE
修改指纹-[alibaba-fastjson]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#48]
### 测试目标

https://fofa.info/result?qbase64=Ym9keT0iZmFzdGpzb24tdmVyc2lvbiI%3D

### 指纹的Yaml规则

 ```yaml
name: alibaba-fastjson
priority: 3
nuclei_tags:
  - - fastjson
fingerprint:
  - path: /
    request_method: get
    request_headers: { }
    request_data: ''
    status_code: 0
    headers: { }
    keyword:
      - js/base/fastjson
    favicon_hash: [ ]
  - path: /
    request_method: get
    request_headers: { }
    request_data: ''
    status_code: 0
    headers: { }
    keyword:
      - var json = json.parse
    favicon_hash: [ ]
  - path: /
    request_method: get
    request_headers: { }
    request_data: ''
    status_code: 0
    headers: { }
    keyword:
      - com.alibaba.fastjson.JSONException
    favicon_hash: [ ]
  - path: /
    request_method: get
    request_headers: { }
    request_data: ''
    status_code: 0
    headers: { }
    keyword:
      - unclosed string
    favicon_hash: [ ]
  - path: /
    request_method: post
    request_headers: { }
    request_data: e0B0eXBlOmphdmEubGFuZy5BdXRvQ2xvc2VhYmxlCg==
    status_code: 0
    headers: { }
    keyword:
      - fastjson
      - version
    favicon_hash: [ ]
```
