### ISSUE TITLE
提交指纹-[apollo-adminservice]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#49]
### 测试目标

http://dev.rummyshows.xyz:8091/

### 指纹的Yaml规则

 ```yaml
name: apollo-adminservice
priority: 3
nuclei_tags:
 - [apollo]
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {"Content-Length":"19"}
   keyword:
     - 'apollo-adminservice'
   favicon_hash: []
```
