### ISSUE TITLE
提交指纹-[apollo-configservice]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#50]
### 测试目标

http://flyernetboom.netboom.ltd:8080/

### 指纹的Yaml规则

 ```yaml
name: apollo-configservice
priority: 3
nuclei_tags:
 - [apollo]
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {"Content-Type":"text/html"}
   keyword:
     - '<title>Eureka</title>'
     - '<td><b>APOLLO-ADMINSERVICE</b></td>'
     - '<td><b>APOLLO-CONFIGSERVICE</b></td>'
   favicon_hash: []
```
