### ISSUE TITLE
提交指纹-[jupyter-notebook]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#51]
### 测试目标

http://jupyter.94life.press/

### 指纹的Yaml规则

 ```yaml
name: jupyter-notebook
priority: 3
nuclei_tags:
  - [jupyter]
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <div id="ipython-main-app" class="container">
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <div id="ipython_notebook" class="nav navbar-brand">
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Jupyter Notebook</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword: []
    favicon_hash: ["97c6417ed01bdc0ae3ef32ae4894fd03"]
```
