### ISSUE TITLE
提交指纹-[mcms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#53]
### 测试目标

https://47.92.236.80/

### 指纹的Yaml规则

 ```yaml
name: mcms
priority: 3
nuclei_tags:
 - [mcms]
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 200
   headers: {}
   keyword:
    - '/mcms/search.do" method='
   favicon_hash: []
```
