### ISSUE TITLE
提交指纹-[nessus]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#56]
### 测试目标

https://65.36.178.234:8834/

### 指纹的Yaml规则

 ```yaml
name: nessus
priority: 3
nuclei_tags:
 - []
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 200
   headers: {}
   keyword:
    - '<title>Nessus</title>'
   favicon_hash: []
```
