### ISSUE TITLE
提交指纹-[xstream]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#58]
### 测试目标

https://54.69.100.53/

### 指纹的Yaml规则

 ```yaml
name: xstream
priority: 3
nuclei_tags:
  - - xstream
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
    - com.thoughtworks.xstream
    - Exception
   favicon_hash: []
```
