### ISSUE TITLE
提交指纹-[xray-clandbeta]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#59]
### 测试目标

http://124.220.180.112:8001/

### 指纹的Yaml规则

 ```yaml
name: xray-clandbeta
priority: 3
nuclei_tags:
  - - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '/cland/css/'
    favicon_hash: ["2fdaf65cb9342b76c97b027fc6f545e8"]
```
