### ISSUE TITLE
提交指纹-[nexpose]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#60]
### 测试目标

https://20.185.37.184/

### 指纹的Yaml规则

 ```yaml
name: nexpose
priority: 3
nuclei_tags:
  - - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '<label for="nexposeccusername">Username</label>'
    favicon_hash: ["f64ce96bbacc76d6db4d4eb0e78881da"]
```
