### ISSUE TITLE
提交指纹-[rengine]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#61]
### 测试目标

https://178.18.245.16/

### 指纹的Yaml规则

 ```yaml
name: rengine
priority: 3
nuclei_tags:
  - - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - '>Login to reNgine.</h5>'
    favicon_hash: []
```
