### ISSUE TITLE
提交指纹-[awvs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#62]
### 测试目标

https://waves.telkom.co.id:1935

### 指纹的Yaml规则

 ```yaml
name: awvs
priority: 3
nuclei_tags:
  - - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Acunetix</title>
    favicon_hash: []
```
