### ISSUE TITLE
提交指纹-[arl]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#63]
### 测试目标

https://l.3ttech.cn:5003

### 指纹的Yaml规则

 ```yaml
name: arl
priority: 3
nuclei_tags:
  - - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>资产灯塔系统</title>
    favicon_hash: []
```
