### ISSUE TITLE
提交指纹-[mlflow]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#64]
### 测试目标

https://mlflow.ovision-gis.com/

### 指纹的Yaml规则

 ```yaml
name: mlflow
priority: 3
nuclei_tags:
  - - mlflow
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
    - <title>MLflow</title>
   favicon_hash: []
```
