### ISSUE TITLE
提交指纹-[appwrite]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#65]
### 测试目标

https://kolorowanki.art:1443/

### 指纹的Yaml规则

 ```yaml
name: appwrite
priority: 3
nuclei_tags:
  - - appwrite
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Sign In - Appwrite</title>
    favicon_hash: []
```
