### ISSUE TITLE
提交指纹-[hfs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#66]
### 测试目标

http://emp.cmsrict.com:9000/

### 指纹的Yaml规则

 ```yaml
name: hfs
priority: 3
nuclei_tags:
  - - hfs
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>HFS /</title>
    favicon_hash: []
```
