### ISSUE TITLE
提交指纹-[powerjob]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#67]
### 测试目标

http://ec2-3-7-234-208.ap-south-1.compute.amazonaws.com:7700/

### 指纹的Yaml规则

 ```yaml
name: powerjob
priority: 3
nuclei_tags:
  - []
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>PowerJob</title>
   favicon_hash: []
```
