### ISSUE TITLE
提交指纹-[zeppelin]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#68]
### 测试目标

https://ec2-15-165-64-98.ap-northeast-2.compute.amazonaws.com/

### 指纹的Yaml规则

 ```yaml
name: zeppelin
priority: 3
nuclei_tags:
 - []
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
    - <title ng-bind="$root.pageTitle">Zeppelin</title>
  favicon_hash: []
```
