### ISSUE TITLE
提交指纹-[papercut]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#69]
### 测试目标

https://128.97.186.31

### 指纹的Yaml规则

 ```yaml
name: papercut
priority: 3
nuclei_tags:
  - - papercut
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <h1 id="papercut-user-login-title">
    favicon_hash: []
```
