### ISSUE TITLE
提交指纹-[apache-superset]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#71]
### 测试目标

http://data.bio-merry.com:8088/

### 指纹的Yaml规则

 ```yaml
name: apache-superset
priority: 3
nuclei_tags:
  - - superset
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Superset</title>
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - src="/static/assets/images/superset-logo-
    favicon_hash: []
```
