### ISSUE TITLE
提交指纹-[vmware-aria-operations]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#74]
### 测试目标

https://ec2-34-208-237-52.us-west-2.compute.amazonaws.com/

### 指纹的Yaml规则

 ```yaml
name: vmware-aria-operations
priority: 3
nuclei_tags:
  - - aria
fingerprint:
  - path: '/auth/login?redirect=https%3A%2F%2F'
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - /vmw-aria-operations-applications-prod-icon-horiz.svg"
    favicon_hash: []
```
