### ISSUE TITLE
提交指纹-[apache-ranger]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#75]
### 测试目标

http://43.153.31.188:6080/

### 指纹的Yaml规则

 ```yaml
name: apache-ranger
priority: 3
nuclei_tags:
 - - ranger
   - apache
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <img src="images/ranger_logo.png" alt="Ranger logo">
   favicon_hash: []
```
