### ISSUE TITLE
提交指纹-[dell-idrac]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#76]
### 测试目标

https://45.35.66.186/

### 指纹的Yaml规则

 ```yaml
name: dell-idrac
priority: 3
nuclei_tags:
 - - idrac
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>Dell Remote Management Controller</title>
   favicon_hash: []
```
