### ISSUE TITLE
提交指纹-[frp]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#77]
### 测试目标

http://siyuan.nasv4.sslcheese.xyz:7500/

### 指纹的Yaml规则

 ```yaml
name: frp
priority: 3
nuclei_tags:
 - - frp
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>frps dashboard</title>
   favicon_hash: []
```
