### ISSUE TITLE
提交指纹-[apache-storm]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#78]
### 测试目标

http://rhclw.busonline.host:8081/

### 指纹的Yaml规则

 ```yaml
name: apache-storm
priority: 3
nuclei_tags:
 - - storm
   - apache
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>Storm UI</title>
   favicon_hash: []
```
