### ISSUE TITLE
提交指纹-[jupyterhub]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#79]
### 测试目标

https://v2jp001.xinchanjiao.com/

### 指纹的Yaml规则

 ```yaml
name: jupyterhub
priority: 3
nuclei_tags:
 - - jupyterhub
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>JupyterHub</title>
   favicon_hash: []
```
