### ISSUE TITLE
提交指纹-[kkfileview]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#86]
### 测试目标

http://kkfile.zqxx.wuguobao.com/

### 指纹的Yaml规则

 ```yaml
name: kkfileview
priority: 3
nuclei_tags:
 - - kkFileView
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - "repo: 'kkFileView'"
   favicon_hash: []
```
