### ISSUE TITLE
提交指纹-[nextjs]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#87]
### 测试目标

http://ip.moeyy.cn:3021/

### 指纹的Yaml规则

 ```yaml
name: nextjs
priority: 3
nuclei_tags:
 - - nextjs
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
    headers:
      X-Powered-By: Next.js
    keyword: []
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   keyword:
     - <meta name="next-head-count
   favicon_hash: []
```
