### ISSUE TITLE
提交指纹-[ruby-on-rails]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#89]
### 测试目标

https://nine-god.com

### 指纹的Yaml规则

 ```yaml
name: ruby-on-rails
priority: 3
nuclei_tags:
 - - rails
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - content="Ruby on Rails
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - alt="Ruby on Rails
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <title>Ruby on Rails</title>
   favicon_hash: []
```
