### ISSUE TITLE
提交指纹-[maccms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#90]
### 测试目标

https://www.zyzliz.com/

### 指纹的Yaml规则

 ```yaml
name: maccms
priority: 3
nuclei_tags:
 - - maccmsv10
 - - maccms
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <script>var maccms={"path
   favicon_hash: []
```
