### ISSUE TITLE
提交指纹-[vmware-site-recovery-manager]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#91]
### 测试目标

https://202.58.80.77/

### 指纹的Yaml规则

 ```yaml
name: vmware-site-recovery-manager
priority: 3
nuclei_tags:
 - - siterecovery
 - - recovery
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <header alt="VMware Site Recovery Manager
   favicon_hash: []
```
