### ISSUE TITLE
提交指纹-[werkzeug]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#92]
### 测试目标

http://47.92.162.5:5002/

### 指纹的Yaml规则

 ```yaml
name: werkzeug
priority: 3
nuclei_tags:
 - - werkzeug
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers:
     Server: Werkzeug
   keyword: []
   favicon_hash: []
```
