### ISSUE TITLE
提交指纹-[metinfo]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#93]
### 测试目标

http://amococd.com/

### 指纹的Yaml规则

 ```yaml
name: metinfo
priority: 3
nuclei_tags:
 - - metinfo
fingerprint:
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <meta name="generator" content="MetInfo
   favicon_hash: []
 - path: /
   request_method: get
   request_headers: {}
   request_data: ''
   status_code: 0
   headers: {}
   keyword:
     - <div class="powered_by_metinfo"></div>
   favicon_hash: []
```
