### ISSUE TITLE
提交指纹-[umami]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#94]
### 测试目标

http://ericmurphy.xyz:3000/

### 指纹的Yaml规则

 ```yaml
name: umami
priority: 3
nuclei_tags:
- - umami
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword: []
  favicon_hash: 
    - e7acd200faa2134fc17bce2e39304292
```
