### ISSUE TITLE
提交指纹-[tableau]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#95]
### 测试目标

https://dev.tableau.pwc.it/

### 指纹的Yaml规则

 ```yaml
name: tableau
priority: 3
nuclei_tags:
- - tableau
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword: []
  favicon_hash: 
    - 783f669ae8336979325ef497a5e43037
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword: 
    - src="/javascripts/api/tableau-
  favicon_hash: []
```
