### ISSUE TITLE
提交指纹-[doccms]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#96]
### 测试目标

http://horizoutest.horizou.cn/

### 指纹的Yaml规则

 ```yaml
name: doccms
priority: 3
nuclei_tags:
- - doccms
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword: 
    - Power by DocCms x1.0&grysoft
  favicon_hash: []
```
