### ISSUE TITLE
修改指纹-[adminer]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#98]
### 测试目标

http://49.234.37.89

### 指纹的Yaml规则

 ```yaml
name: adminer
priority: 1
nuclei_tags:
  - - adminer
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - ://www.adminer.org/' target="_blank" rel="noreferrer
    favicon_hash: []
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      Content-Security-Policy: script-src 'self' 'unsafe-inline' 'nonce-
    keyword: []
    favicon_hash: []
  - path: /adminer/index.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 200
    headers:
      Content-Security-Policy: script-src 'self' 'unsafe-inline' 'nonce-
    keyword: []
    favicon_hash: []
  - path: /adminer.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 200
    headers:
      Content-Security-Policy: script-src 'self' 'unsafe-inline' 'nonce-
    keyword: []
    favicon_hash: []
  - path: /tools/adminer.php
    request_method: head
    request_headers: {}
    request_data: ''
    status_code: 200
    headers:
      Content-Security-Policy: script-src 'self' 'unsafe-inline' 'nonce-
    keyword: []
    favicon_hash: []
```
