### ISSUE TITLE
提交指纹-[xdebug]

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#99]
### 测试目标

https://xiaz1990.xyz/

### 指纹的Yaml规则

 ```yaml
name: xdebug
priority: 1
nuclei_tags:
  - - xdebug
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers:
      X-Xdebug-Profile-Filename: /
    keyword: []
    favicon_hash: []
```
